Repository ON-GI/BackEnd, pull requests merged in 2025-02, with the labels that each got.

#2 [chore #1] CI/CD 적용
  .github/workflows/docker-deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/resources/application.properties
  src/main/resources/templates/home.html
Labels: chore

#8 Feature/#4
  build.gradle
  src/main/java/com/ongi/backend/BackendApplication.java
  src/main/java/com/ongi/backend/controller/CaregiverController.java
  src/main/java/com/ongi/backend/dto/caregiver/CaregiverLicenseDto.java
  src/main/java/com/ongi/backend/dto/caregiver/CaregiverRequestDto.java
  src/main/java/com/ongi/backend/dto/caregiver/CaregiverWorkConditionDto.java
  src/main/java/com/ongi/backend/dto/caregiver/WorkRegionDto.java
  src/main/java/com/ongi/backend/dto/caregiver/WorkTimeDto.java
  src/main/java/com/ongi/backend/entity/caregiver/Caregiver.java
  src/main/java/com/ongi/backend/entity/caregiver/CaregiverCareer.java
  src/main/java/com/ongi/backend/entity/caregiver/CaregiverLicense.java
  src/main/java/com/ongi/backend/entity/caregiver/CaregiverWorkCondition.java
  src/main/java/com/ongi/backend/entity/caregiver/WorkRegion.java
  src/main/java/com/ongi/backend/entity/caregiver/WorkTime.java
  src/main/java/com/ongi/backend/entity/common/BaseEntity.java
  src/main/java/com/ongi/backend/repository/caregiver/CaregiverLicenseRepository.java
  src/main/java/com/ongi/backend/repository/caregiver/CaregiverRepository.java
  src/main/java/com/ongi/backend/repository/caregiver/CaregiverRepositoryCustom.java
  src/main/java/com/ongi/backend/repository/caregiver/CaregiverRepositoryImpl.java
  src/main/java/com/ongi/backend/repository/caregiver/CaregiverWorkConditionRepository.java
  src/main/java/com/ongi/backend/repository/caregiver/WorkRegionRepository.java
  src/main/java/com/ongi/backend/repository/caregiver/WorkTimeRepository.java
  src/main/java/com/ongi/backend/service/CaregiverService.java
Labels: feature

#9 Feature/#6
  src/main/java/com/ongi/backend/controller/CaregiverController.java
  src/main/java/com/ongi/backend/dto/caregiver/CaregiverRequestDto.java
  src/main/java/com/ongi/backend/dto/caregiver/LicenseRequestDto.java
  src/main/java/com/ongi/backend/dto/caregiver/LicenseResponseDto.java
  src/main/java/com/ongi/backend/dto/caregiver/WorkConditionRequestDto.java
  src/main/java/com/ongi/backend/dto/caregiver/WorkConditionResponseDto.java
  src/main/java/com/ongi/backend/dto/caregiver/WorkRegionRequestDto.java
  src/main/java/com/ongi/backend/dto/caregiver/WorkRegionResponseDto.java
  src/main/java/com/ongi/backend/dto/caregiver/WorkTimeRequestDto.java
  src/main/java/com/ongi/backend/dto/caregiver/WorkTimeResponseDto.java
  src/main/java/com/ongi/backend/entity/caregiver/CaregiverWorkCondition.java
  src/main/java/com/ongi/backend/repository/caregiver/CaregiverWorkConditionRepository.java
  src/main/java/com/ongi/backend/repository/caregiver/WorkRegionRepository.java
  src/main/java/com/ongi/backend/repository/caregiver/WorkTimeRepository.java
  src/main/java/com/ongi/backend/service/CaregiverService.java
  src/main/java/com/ongi/backend/service/CaregiverWorkService.java
Labels: feature

#17 Feature/#5
  build.gradle
  src/main/java/com/ongi/backend/common/config/S3Config.java
  src/main/java/com/ongi/backend/common/exception/FileUploadErrorCase.java
  src/main/java/com/ongi/backend/common/service/FileUploadService.java
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
Labels: feature

#20 [feat #13] 요양보호사 아이디 중복 확인 API 구현
  build.gradle
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/request/ValidateIdRequestDto.java
  src/main/java/com/ongi/backend/domain/caregiver/exception/CaregiverErrorCase.java
  src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepository.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
Labels: feature

#21 [refactor #12] 요양보호사 회원가입 api 수정
  build.gradle
  src/main/java/com/ongi/backend/common/config/PasswordEncoderConfig.java
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/request/CaregiverRequestDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/request/LicenseRequestDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/request/WorkConditionRequestDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/LicenseResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/WorkConditionResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverCareer.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverLicense.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverWorkCondition.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/CaregiverCareer.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/CaregiverWorkConditionPayType.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/DailyLivingAssistanceType.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/FeedingAssistanceType.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/LicenseType.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/MobilityAssistanceType.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/ToiletingAssistanceType.java
  src/main/java/com/ongi/backend/domain/caregiver/exception/CaregiverErrorCase.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
Labels: refactor

#23 [fix #22] 서비스 로깅 AOP 버그 수정
  src/main/java/com/ongi/backend/common/aop/LoggingAspect.java
Labels: fix

#25 [feat #24] 요양보호사 로그인 구현
  build.gradle
  src/main/java/com/ongi/backend/common/security/JwtTokenizer.java
  src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
  src/main/java/com/ongi/backend/domain/auth/dto/LoginTokensDto.java
  src/main/java/com/ongi/backend/domain/auth/dto/request/CaregiverLoginRequest.java
  src/main/java/com/ongi/backend/domain/auth/dto/response/CaregiverLoginResponse.java
  src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
  src/main/java/com/ongi/backend/domain/auth/entity/enums/UserType.java
  src/main/java/com/ongi/backend/domain/auth/exception/AuthErrorCase.java
  src/main/java/com/ongi/backend/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/LicenseType.java
  src/main/java/com/ongi/backend/domain/caregiver/exception/CaregiverErrorCase.java
  src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepository.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
Labels: feature

#27 [feat #] jwt 인증, 인가 추가
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/common/config/SwaggerConfig.java
  src/main/java/com/ongi/backend/common/security/CustomAccessDeniedHandler.java
  src/main/java/com/ongi/backend/common/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/ongi/backend/common/security/JwtAuthorizationFilter.java
  src/main/java/com/ongi/backend/common/security/JwtTokenizer.java
  src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
  src/main/java/com/ongi/backend/domain/auth/entity/enums/Authority.java
  src/main/java/com/ongi/backend/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
Labels: feature

#30 [feat #28] 로그아웃 구현
  src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
  src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
Labels: feature

#32 [feat #31] 인증 토큰 재발급 로직 구현
  src/main/java/com/ongi/backend/common/security/JwtTokenizer.java
  src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
  src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
  src/main/java/com/ongi/backend/domain/auth/entity/enums/Authority.java
  src/main/java/com/ongi/backend/domain/auth/exception/AuthErrorCase.java
  src/main/java/com/ongi/backend/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
Labels: feature

#34 [refactor #33] 요양보호사 회원가입 수정
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/request/CaregiverSignupRequestDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/request/InformationRequestDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/request/OptionalRequestDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/CaregiverSignupResponse.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/LicenseResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverInformation.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverLicense.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverOptional.java
  src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverInformationRepository.java
  src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverOptionalRepository.java
  src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepository.java
  src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepositoryCustom.java
  src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepositoryImpl.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
Labels: refactor

#37 [refactor #36] 인증/인가 수정
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/common/security/CustomAccessDeniedHandler.java
  src/main/java/com/ongi/backend/common/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
Labels: refactor

#38 [feat #29] 어르신 정보 CRUD 기능 구현
  .DS_Store
  .gitignore
  src/main/java/com/ongi/backend/common/entity/Gender.java
  src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
  src/main/java/com/ongi/backend/domain/center/entity/Center.java
  src/main/java/com/ongi/backend/domain/center/service/CenterService.java
  src/main/java/com/ongi/backend/domain/senior/controller/SeniorController.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorCareConditionRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorDiseaseRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorCareConditionResponseDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorCareTimeResponseDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorDiseaseResponseDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorResponseDto.java
  src/main/java/com/ongi/backend/domain/senior/entity/DiseaseDementiaMapping.java
  src/main/java/com/ongi/backend/domain/senior/entity/Senior.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorCareCondition.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorCareTime.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorCareTypeMapping.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorDisease.java
  src/main/java/com/ongi/backend/domain/senior/entity/enums/DementiaSymptom.java
  src/main/java/com/ongi/backend/domain/senior/entity/enums/GradeType.java
  src/main/java/com/ongi/backend/domain/senior/entity/enums/Residence.java
  src/main/java/com/ongi/backend/domain/senior/entity/enums/ResidenceType.java
  src/main/java/com/ongi/backend/domain/senior/entity/enums/SeniorCareDetail.java
  src/main/java/com/ongi/backend/domain/senior/entity/enums/SeniorCareType.java
  src/main/java/com/ongi/backend/domain/senior/exception/SeniorErrorCase.java
  src/main/java/com/ongi/backend/domain/senior/repository/SeniorCareConditionRepository.java
  src/main/java/com/ongi/backend/domain/senior/repository/SeniorDiseaseRepository.java
  src/main/java/com/ongi/backend/domain/senior/repository/SeniorRepository.java
  src/main/java/com/ongi/backend/domain/senior/repository/SeniorRepositoryCustom.java
  src/main/java/com/ongi/backend/domain/senior/repository/SeniorRepositoryImpl.java
  src/main/java/com/ongi/backend/domain/senior/service/SeniorService.java
Labels: feature

#41 [fix] center 관련 로직 수정
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
  src/main/java/com/ongi/backend/domain/center/dto/request/CenterSearchCondition.java
  src/main/java/com/ongi/backend/domain/center/exception/CenterErrorCase.java
  src/main/java/com/ongi/backend/domain/center/service/CenterService.java
Labels: fix

#42 [feature #16] 요양 보호사, 어르신 생성 자동화
  src/main/java/com/ongi/backend/common/initializer/CaregiverDataInitializer.java
  src/main/java/com/ongi/backend/common/initializer/CenterDataInitializer.java
  src/main/java/com/ongi/backend/common/initializer/SeniorDataInitializer.java
  src/main/java/com/ongi/backend/domain/senior/entity/Senior.java
  src/main/resources/sql/caregiver.sql
  src/main/resources/sql/caregiver_work_condition.sql
  src/main/resources/sql/senior.sql
Labels: feature

#44 [feat #35] 사회복지사 로그인 구현
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/common/enums/Authority.java
  src/main/java/com/ongi/backend/common/enums/Gender.java
  src/main/java/com/ongi/backend/common/security/JwtAuthorizationFilter.java
  src/main/java/com/ongi/backend/common/security/JwtTokenizer.java
  src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
  src/main/java/com/ongi/backend/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
  src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
  src/main/java/com/ongi/backend/domain/center/dto/request/CenterSearchCondition.java
  src/main/java/com/ongi/backend/domain/center/entity/Center.java
  src/main/java/com/ongi/backend/domain/center/exception/CenterErrorCase.java
  src/main/java/com/ongi/backend/domain/center/service/CenterService.java
  src/main/java/com/ongi/backend/domain/centerstaff/controller/CenterStaffController.java
  src/main/java/com/ongi/backend/domain/centerstaff/dto/request/CenterStaffSignupRequest.java
  src/main/java/com/ongi/backend/domain/centerstaff/dto/response/CenterStaffResponse.java
  src/main/java/com/ongi/backend/domain/centerstaff/dto/response/CenterStaffSignupResponse.java
  src/main/java/com/ongi/backend/domain/centerstaff/entity/CenterStaff.java
  src/main/java/com/ongi/backend/domain/centerstaff/exception/CenterStaffErrorCase.java
  src/main/java/com/ongi/backend/domain/centerstaff/repository/CenterStaffRepository.java
  src/main/java/com/ongi/backend/domain/centerstaff/service/CenterStaffService.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorResponseDto.java
  src/main/java/com/ongi/backend/domain/senior/entity/Senior.java
Labels: feature

#53 [feat #] 요양보호사 마이페이지 api 구현
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/request/CaregiverUpdateRequestDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/CaregiverResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/InformationResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/LicenseResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/OptionalResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverInformation.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverOptional.java
  src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepository.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
Labels: feature

#54 [feat #43] JWT 토큰에서 centerId 추출해서 사용하는 로직 구현
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/common/security/JwtAuthorizationFilter.java
  src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
  src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
  src/main/java/com/ongi/backend/domain/senior/controller/SeniorController.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorResponseDto.java
  src/main/java/com/ongi/backend/domain/senior/entity/Senior.java
  src/main/java/com/ongi/backend/domain/senior/exception/SeniorErrorCase.java
  src/main/java/com/ongi/backend/domain/senior/service/SeniorService.java
Labels: feature

#56 [feat #55] 어르신 관리자 연락처 필드 추가
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorResponseDto.java
  src/main/java/com/ongi/backend/domain/senior/entity/Senior.java
Labels: feature

#58 [fix] 센터 생성 코드가 local에서만 동작하도록 수정
  src/main/java/com/ongi/backend/common/initializer/CenterDataInitializer.java
Labels: fix

#59 [feat] CloudWatch 연동, CORS 설정 변경
  src/main/java/com/ongi/backend/common/config/LoggingFilterConfig.java
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
Labels: feature

#60 [feat] CloudWatch 연동, CORS 설정 변경
  src/main/java/com/ongi/backend/common/config/LoggingFilterConfig.java
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/common/initializer/CenterDataInitializer.java
Labels: fix, feature

#61 [fix] CORS 설정 변경
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
Labels: fix

#62 [fix] CORS 설정 변경
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
Labels: fix

#64 [fix #63] Controller의 응답값 수정
  src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
  src/main/java/com/ongi/backend/domain/senior/controller/SeniorController.java
Labels: fix

#66 [fix] 요양보호사 회원가입 수정
  src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverInformation.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverOptional.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
Labels: fix

#69 [fix] 토큰 재발급, 배변 보조 타입 오류 수정
  src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/enums/ToiletingAssistanceType.java
Labels: fix

#75 [fix] 토큰 재발급, 로그인 인증 타입 오류 수정
  src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
  src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
Labels: fix

#77 [feat #72] 센터장 회원가입 구현
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
  src/main/java/com/ongi/backend/domain/center/dto/request/CenterRequestDto.java
  src/main/java/com/ongi/backend/domain/center/service/CenterService.java
  src/main/java/com/ongi/backend/domain/centerstaff/controller/CenterStaffController.java
  src/main/java/com/ongi/backend/domain/centerstaff/dto/response/CenterStaffSignupResponse.java
  src/main/java/com/ongi/backend/domain/centerstaff/service/CenterStaffService.java
Labels: feature

#78 [feat #74] 요양보호사 프로필 링크 조회
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/ProfileUrlResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
Labels: feature

#79 [feat #47] 매칭 CRUD 구현
  src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
  src/main/java/com/ongi/backend/domain/matching/controller/CaregiverMatchingController.java
  src/main/java/com/ongi/backend/domain/matching/controller/CenterMatchingController.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingAdjustRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingCareTimeRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingConditionRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/MatchingCareTimeResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/MatchingThumbnailResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/entity/Matching.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingAdjustment.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCareDetail.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCareRegion.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCareTime.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCondition.java
  src/main/java/com/ongi/backend/domain/matching/entity/enums/MatchingStatus.java
  src/main/java/com/ongi/backend/domain/matching/exception/MatchingErrorCase.java
  src/main/java/com/ongi/backend/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ongi/backend/domain/matching/repository/MatchingRepositoryCustom.java
  src/main/java/com/ongi/backend/domain/matching/repository/MatchingRepositoryImpl.java
  src/main/java/com/ongi/backend/domain/matching/service/MatchingService.java
  src/main/java/com/ongi/backend/domain/senior/controller/SeniorController.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorMatchingConditionRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorMatchingTimeRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/entity/Senior.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorMatchingCareDetail.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorMatchingCondition.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorMatchingTime.java
  src/main/java/com/ongi/backend/domain/senior/repository/SeniorRepositoryImpl.java
  src/main/java/com/ongi/backend/domain/senior/service/SeniorService.java
Labels: feature

#80 [feat] 매칭 CRUD 기능 배포 서버에 반영
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
  src/main/java/com/ongi/backend/domain/caregiver/dto/response/ProfileUrlResponseDto.java
  src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
  src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java
  src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
  src/main/java/com/ongi/backend/domain/center/dto/request/CenterRequestDto.java
  src/main/java/com/ongi/backend/domain/center/service/CenterService.java
  src/main/java/com/ongi/backend/domain/centerstaff/controller/CenterStaffController.java
  src/main/java/com/ongi/backend/domain/centerstaff/dto/response/CenterStaffSignupResponse.java
  src/main/java/com/ongi/backend/domain/centerstaff/service/CenterStaffService.java
  src/main/java/com/ongi/backend/domain/matching/controller/CaregiverMatchingController.java
  src/main/java/com/ongi/backend/domain/matching/controller/CenterMatchingController.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingAdjustRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingCareTimeRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingConditionRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/MatchingCareTimeResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/MatchingThumbnailResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/entity/Matching.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingAdjustment.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCareDetail.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCareRegion.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCareTime.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCondition.java
  src/main/java/com/ongi/backend/domain/matching/entity/enums/MatchingStatus.java
  src/main/java/com/ongi/backend/domain/matching/exception/MatchingErrorCase.java
  src/main/java/com/ongi/backend/domain/matching/repository/MatchingRepository.java
  src/main/java/com/ongi/backend/domain/matching/repository/MatchingRepositoryCustom.java
  src/main/java/com/ongi/backend/domain/matching/repository/MatchingRepositoryImpl.java
  src/main/java/com/ongi/backend/domain/matching/service/MatchingService.java
  src/main/java/com/ongi/backend/domain/senior/controller/SeniorController.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorMatchingConditionRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorMatchingTimeRequestDto.java
  src/main/java/com/ongi/backend/domain/senior/entity/Senior.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorMatchingCareDetail.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorMatchingCondition.java
  src/main/java/com/ongi/backend/domain/senior/entity/SeniorMatchingTime.java
  src/main/java/com/ongi/backend/domain/senior/repository/SeniorRepositoryImpl.java
  src/main/java/com/ongi/backend/domain/senior/service/SeniorService.java
Labels: feature

#82 [feat #73] 관리자 마이페이지 api 구현
  src/main/java/com/ongi/backend/common/config/SecurityConfig.java
  src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
  src/main/java/com/ongi/backend/domain/center/dto/request/CenterEssentialRequestDto.java
  src/main/java/com/ongi/backend/domain/center/dto/request/CenterOptionalRequestDto.java
  src/main/java/com/ongi/backend/domain/center/dto/response/CenterEssentialResponseDto.java
  src/main/java/com/ongi/backend/domain/center/dto/response/CenterOptionalResponseDto.java
  src/main/java/com/ongi/backend/domain/center/dto/response/CenterProfileResponseDto.java
  src/main/java/com/ongi/backend/domain/center/entity/Center.java
  src/main/java/com/ongi/backend/domain/center/entity/enums/CenterGrade.java
  src/main/java/com/ongi/backend/domain/center/exception/CenterErrorCase.java
  src/main/java/com/ongi/backend/domain/center/service/CenterService.java
Labels: feature

#85 [feat] 매칭된 요양보호사 정보 조회 구현
  src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
  src/main/java/com/ongi/backend/domain/matching/controller/CenterMatchingController.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/LicenseResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/MatchingCaregiverInfoResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/WorkConditionResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/service/MatchingService.java
Labels: feature

#86 [hotfix] 매칭된 요양보호사 정보 조회 api 주소 수정
  src/main/java/com/ongi/backend/domain/matching/controller/CenterMatchingController.java
Labels: fix

#89 [feat] 매칭 알고리즘 구현 후 배포서버 반영
  src/main/java/com/ongi/backend/common/enums/Gender.java
  src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
  src/main/java/com/ongi/backend/domain/matching/controller/CaregiverMatchingController.java
  src/main/java/com/ongi/backend/domain/matching/controller/CenterMatchingController.java
  src/main/java/com/ongi/backend/domain/matching/dto/request/MatchingConditionRequestDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/CaregiverMatchingResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/CaregiverWorkTimeResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/LicenseResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/MatchingCaregiverInfoResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/SeniorMatchingDetailResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/dto/response/WorkConditionResponseDto.java
  src/main/java/com/ongi/backend/domain/matching/entity/Matching.java
  src/main/java/com/ongi/backend/domain/matching/entity/MatchingCondition.java
  src/main/java/com/ongi/backend/domain/matching/exception/MatchingErrorCase.java
  src/main/java/com/ongi/backend/domain/matching/repository/MatchingRepositoryCustom.java
  src/main/java/com/ongi/backend/domain/matching/repository/MatchingRepositoryImpl.java
  src/main/java/com/ongi/backend/domain/matching/service/MatchingService.java
  src/main/resources/sql/caregiver.sql
  src/main/resources/sql/caregiver_work_condition.sql
Labels: feature

#91 [fix] ssl 오류 수정
  src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
Labels: fix
